const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  updaterEtat: () => ipcRenderer.invoke('updater:etat'),
  updaterVerifier: () => ipcRenderer.invoke('updater:verifier'),
  updaterTelecharger: () => ipcRenderer.invoke('updater:telecharger'),
  updaterInstallerRedemarrer: () => ipcRenderer.invoke('updater:installer-redemarrer'),
  onUpdaterEtat: (callback) => {
    const handler = (_e, etat) => callback(etat);
    ipcRenderer.on('updater:etat', handler);
    return () => ipcRenderer.removeListener('updater:etat', handler);
  },
  accueilDonnees: () => ipcRenderer.invoke('accueil:donnees'),
  suiviDonnees: () => ipcRenderer.invoke('suivi:donnees'),
  documentsListe: () => ipcRenderer.invoke('documents:liste'),
  rapportJournalier: (dateISO) => ipcRenderer.invoke('rapport:journalier', dateISO),
  rapportPdf: (dateISO) => ipcRenderer.invoke('rapport:pdf', dateISO),
  oeuvreRetrait: (id, data) => ipcRenderer.invoke('oeuvres:retrait', id, data),
  oeuvresRetraitLot: (ids, data) => ipcRenderer.invoke('oeuvres:retrait-lot', ids, data),
  oeuvreReserver: (id, data) => ipcRenderer.invoke('oeuvres:reserver', id, data),
  oeuvreLiberer: (id) => ipcRenderer.invoke('oeuvres:liberer', id),
  appInfos: () => ipcRenderer.invoke('app:infos'),
  iaCopierPourChatGPT: (oeuvreId) => ipcRenderer.invoke('ia:copier-pour-chatgpt', oeuvreId),
  iaCopierPourChatGPTInline: (params) => ipcRenderer.invoke('ia:copier-pour-chatgpt-inline', params),
  iaCopierImageSeulement: (imageDataUrl) => ipcRenderer.invoke('ia:copier-image-seulement', imageDataUrl),
  iaGenererDescription: (oeuvreId) => ipcRenderer.invoke('ia:generer-description', oeuvreId),
  iaGenererDescriptionInline: (params) => ipcRenderer.invoke('ia:generer-description-inline', params),
  iaDefinirCle: (cle) => ipcRenderer.invoke('ia:definir-cle', cle),
  iaEffacerCle: () => ipcRenderer.invoke('ia:effacer-cle'),
  iaCleDefinie: () => ipcRenderer.invoke('ia:cle-definie'),
  ouvrirUrl: (url) => ipcRenderer.invoke('app:ouvrir-url', url),
  ouvrirDossier: (dossier) => ipcRenderer.invoke('app:ouvrir-dossier', dossier),
  appZoom: (facteur) => ipcRenderer.invoke('app:zoom', facteur),
  importChoisirFichier: () => ipcRenderer.invoke('import:choisir-fichier'),
  importExecuter: (path, mode) => ipcRenderer.invoke('import:executer', path, mode),
  backupNow: () => ipcRenderer.invoke('backup:now'),
  backupEtat: () => ipcRenderer.invoke('backup:etat'),
  backupListe: () => ipcRenderer.invoke('backup:liste'),
  backupRestaurer: (chemin) => ipcRenderer.invoke('backup:restaurer', chemin),
  onBackupAlerte: (callback) => {
    const handler = (_e, alerte) => callback(alerte);
    ipcRenderer.on('backup:alerte', handler);
    return () => ipcRenderer.removeListener('backup:alerte', handler);
  },
  artistesListe: (filtres) => ipcRenderer.invoke('artistes:liste', filtres),
  ficheArchiver: (table, id, archive) => ipcRenderer.invoke('fiche:archiver', table, id, archive),
  artisteGet: (id) => ipcRenderer.invoke('artistes:get', id),
  artisteFicheBundle: (id) => ipcRenderer.invoke('artistes:fiche-bundle', id),
  artisteModifier: (id, data) => ipcRenderer.invoke('artistes:modifier', id, data),
  artisteCreer: (data) => ipcRenderer.invoke('artistes:creer', data),
  artisteSupprimer: (id) => ipcRenderer.invoke('artistes:supprimer', id),
  oeuvresListe: (filtres) => ipcRenderer.invoke('oeuvres:liste', filtres),
  oeuvresDetailArtiste: (artisteId) => ipcRenderer.invoke('oeuvres:detail-artiste', artisteId),
  oeuvresParIds: (ids) => ipcRenderer.invoke('oeuvres:par-ids', ids),
  oeuvreGet: (id) => ipcRenderer.invoke('oeuvres:get', id),
  oeuvreFicheBundle: (id) => ipcRenderer.invoke('oeuvres:fiche-bundle', id),
  oeuvreModifier: (id, data) => ipcRenderer.invoke('oeuvres:modifier', id, data),
  oeuvresModifierLot: (modifs) => ipcRenderer.invoke('oeuvres:modifier-lot', modifs),
  oeuvreCreer: (data) => ipcRenderer.invoke('oeuvres:creer', data),
  oeuvreApercuNumeroInventaire: (artisteId) => ipcRenderer.invoke('oeuvres:apercu-numero-inventaire', artisteId),
  oeuvreReserverNumeroInventaire: (artisteId) => ipcRenderer.invoke('oeuvres:reserver-numero-inventaire', artisteId),
  oeuvreSupprimer: (id) => ipcRenderer.invoke('oeuvres:supprimer', id),
  oeuvreMajPreparation: (id, data) => ipcRenderer.invoke('oeuvres:maj-preparation', id, data),
  oeuvreNomFichier: (id) => ipcRenderer.invoke('oeuvres:nom-fichier', id),
  oeuvresTypes: () => ipcRenderer.invoke('oeuvres:types'),
  oeuvresMediums: () => ipcRenderer.invoke('oeuvres:mediums'),
  oeuvresMediumsArtiste: (artisteId) => ipcRenderer.invoke('oeuvres:mediums-artiste', artisteId),
  clientsListe: (filtres) => ipcRenderer.invoke('clients:liste', filtres),
  clientGet: (id) => ipcRenderer.invoke('clients:get', id),
  clientFicheBundle: (id) => ipcRenderer.invoke('clients:fiche-bundle', id),
  clientModifier: (id, data) => ipcRenderer.invoke('clients:modifier', id, data),
  clientCreer: (data) => ipcRenderer.invoke('clients:creer', data),
  clientSupprimer: (id) => ipcRenderer.invoke('clients:supprimer', id),
  ventesListe: () => ipcRenderer.invoke('ventes:liste'),
  venteFicheBundle: (id) => ipcRenderer.invoke('ventes:fiche-bundle', id),
  venteCreer: (data) => ipcRenderer.invoke('ventes:creer', data),
  venteModifier: (id, data) => ipcRenderer.invoke('ventes:modifier', id, data),
  venteMajCycle: (id, data) => ipcRenderer.invoke('ventes:maj-cycle', id, data),
  venteSupprimer: (id) => ipcRenderer.invoke('ventes:supprimer', id),
  venteApercuNumeroFacture: () => ipcRenderer.invoke('ventes:apercu-numero-facture'),
  venteReserverNumeroFacture: () => ipcRenderer.invoke('ventes:reserver-numero-facture'),
  certificatsListeOeuvre: (oeuvreId) => ipcRenderer.invoke('certificats:liste-oeuvre', oeuvreId),
  certificatsListeVente: (venteId) => ipcRenderer.invoke('certificats:liste-vente', venteId),
  certificatCreer: (data) => ipcRenderer.invoke('certificats:creer', data),
  certificatSupprimer: (id) => ipcRenderer.invoke('certificats:supprimer', id),
  certificatApercu: (oeuvreId) => ipcRenderer.invoke('certificats:apercu', oeuvreId),
  pdfCertificatGenerer: (id) => ipcRenderer.invoke('pdf:certificat-generer', id),
  pdfFactureArtisteGenerer: (venteId) => ipcRenderer.invoke('pdf:facture-artiste-generer', venteId),
  pdfCatalogueGenerer: (artisteId) => ipcRenderer.invoke('pdf:catalogue-generer', artisteId),
  pdfAnnexeGenerer: (payload) => ipcRenderer.invoke('pdf:annexe-generer', payload),
  pdfPresentationGenerer: (artisteId) => ipcRenderer.invoke('pdf:presentation-generer', artisteId),
  pdfPochetteGenerer: (venteId) => ipcRenderer.invoke('pdf:pochette-generer', venteId),
  pdfEditerDocument: (spec) => ipcRenderer.invoke('pdf:editer-document', spec),
  pdfPochetteFichier: (venteId, type) => ipcRenderer.invoke('pdf:pochette-fichier', venteId, type),
  pdfPochetteDossierInfos: (venteId) => ipcRenderer.invoke('pdf:pochette-dossier-infos', venteId),
  pdfPochetteDossierSupprimer: (chemin) => ipcRenderer.invoke('pdf:pochette-dossier-supprimer', chemin),
  pdfOuvrir: (cheminPdf) => ipcRenderer.invoke('pdf:ouvrir', cheminPdf),
  pdfRevelerDansExplorateur: (cheminPdf) => ipcRenderer.invoke('pdf:reveler-dans-explorateur', cheminPdf),
  photoChoisir: (table, id) => ipcRenderer.invoke('photo:choisir', { table, id }),
  photoEffacer: (table, id) => ipcRenderer.invoke('photo:effacer', { table, id }),
  photoLireFichier: () => ipcRenderer.invoke('photo:lire-fichier'),
  photoLirePourRecadrage: (table, id) => ipcRenderer.invoke('photo:lire-pour-recadrage', { table, id }),
  photoEnregistrerRecadree: (table, id, cropDataUrl, originaleDataUrl) =>
    ipcRenderer.invoke('photo:enregistrer-recadree', { table, id, cropDataUrl, originaleDataUrl }),
  configGet: () => ipcRenderer.invoke('config:get'),
  configSauver: (partiel) => ipcRenderer.invoke('config:sauver', partiel),
  catalogueVerifier: () => ipcRenderer.invoke('catalogue:verifier'),
  catalogueRefuser: (id) => ipcRenderer.invoke('catalogue:refuser', id),
  catalogueCharger: () => ipcRenderer.invoke('catalogue:charger'),
  configChoisirDossier: () => ipcRenderer.invoke('config:choisir-dossier'),
  outilsTauxChange: () => ipcRenderer.invoke('outils:taux-change'),
  outilsTauxChangeRecuperer: () => ipcRenderer.invoke('outils:taux-change-recuperer'),
  outilsCopierTexte: (texte) => ipcRenderer.invoke('outils:copier-texte', texte),
  donneesEmplacement: () => ipcRenderer.invoke('donnees:emplacement'),
  donneesChoisirDestination: () => ipcRenderer.invoke('donnees:choisir-destination'),
  donneesValiderDestination: (dest) => ipcRenderer.invoke('donnees:valider-destination', dest),
  donneesDeplacer: (dest) => ipcRenderer.invoke('donnees:deplacer', dest),
  donneesChoisirDossierExistant: () => ipcRenderer.invoke('donnees:choisir-dossier-existant'),
  donneesAdopter: (dossier) => ipcRenderer.invoke('donnees:adopter', dossier),
  configChoisirLogo: () => ipcRenderer.invoke('config:choisir-logo'),
  backupRedemarrer: () => ipcRenderer.invoke('backup:redemarrer'),
  securiteEtat: () => ipcRenderer.invoke('securite:etat'),
  securiteDefinirCode: (code) => ipcRenderer.invoke('securite:definir-code', code),
  securiteRetirerCode: () => ipcRenderer.invoke('securite:retirer-code'),
  securiteVerifierCode: (code) => ipcRenderer.invoke('securite:verifier-code', code),
  securiteDefinirOptions: (opts) => ipcRenderer.invoke('securite:definir-options', opts),
  securiteDefinirQuestion: (q, r) => ipcRenderer.invoke('securite:definir-question', q, r),
  securiteRetirerQuestion: () => ipcRenderer.invoke('securite:retirer-question'),
  securiteVerifierReponse: (r) => ipcRenderer.invoke('securite:verifier-reponse', r),
  securiteReinitialiserCode: (r, code) => ipcRenderer.invoke('securite:reinitialiser-code', r, code),
  onSecuriteVerrouiller: (callback) => {
    const handler = () => callback();
    ipcRenderer.on('securite:verrouiller', handler);
    return () => ipcRenderer.removeListener('securite:verrouiller', handler);
  },
});
